<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <Compile
            Include="../../shared/Utility/src/Utility/Caching/*.cs;../../shared/Utility/src/Utility/Cryptography/*.cs"
            Link="Shared/%(Filename)%(Extension)"
        />
        <Compile
            Include="../../src/MuvluvMod/Services/TranslationCache.cs"
            Link="Production/TranslationCache.cs"
        />
        <Compile
            Include="../../src/MuvluvMod/Services/TranslationPaths.cs"
            Link="Production/TranslationPaths.cs"
        />
        <Compile
            Include="../../src/MuvluvMod/Services/TranslationManifest.cs"
            Link="Production/TranslationManifest.cs"
        />
        <Compile
            Include="../../src/MuvluvMod/Services/TranslationHash.cs"
            Link="Production/TranslationHash.cs"
        />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" PrivateAssets="all" />
    </ItemGroup>
</Project>
